services:
  p_1_1:
    build:
      context: .
    image: dcr-babel
    hostname: P_1_1
    command:
      - role=P
      - id=1
      - cid=1
    ports:
      - "8080:1234"
    networks:
      - dcr-network
  p_2_1:
    build:
      context: .
    image: dcr-babel
    hostname: P_2_1
    command:
      - role=P
      - id=2
      - cid=1
    ports:
      - "8081:1234"
    networks:
      - dcr-network
  p_3_1:
    build:
      context: .
    image: dcr-babel
    hostname: P_3_1
    command:
      - role=P
      - id=3
      - cid=1
    ports:
      - "8082:1234"
    networks:
      - dcr-network


networks:
  dcr-network:
    name: tardis-babel-backend-net
    external: true
