version: '3.4'

services:
  tardisdcr:
    image: tardisdcr
    build:
      context: .
      dockerfile: ./Dockerfile
    # environment:
    #   JAVA_OPTS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005,quiet=y
    ports:
      - 1234:8080
      # - 5005:5005
    hostname: "Plant_1"
    tty: true
    environment:
      interface: "eth0"
      target-name: "Plant(1)"
      name: "Plant_1"
    